openziti/helm-charts

- charts/reflect/Chart.yaml
Deleting the stray Ziti identity file from the reflectz chart triggered a release cycle for that chart which failed because the prior version already exists so this PR merely bumps the version so that the chart-releaser action will succeed.
> bump reflectz chart version

- charts/hello-toy/.helmignore
- charts/hello-toy/Chart.yaml
- charts/hello-toy/templates/NOTES.txt
- charts/hello-toy/templates/_helpers.tpl
- charts/hello-toy/templates/deployment.yaml
- charts/hello-toy/templates/service.yaml
- charts/hello-toy/templates/serviceaccount.yaml
- charts/hello-toy/values.yaml
Add the hello web app chart so that it can be conveniently deployed for demos and tutorials where the client is a web browser. This allows us to shift focus to the OpenZiti charts repo and begin using the preferred tunneler `ziti-edge-tunnel`. For example, NF tutorials like https://developer.netfoundry.io/guides/kubernetes/ can be changed to use this Helm charts repo and it's not necessary to add multiple Helm repos because this repo will have both tunneler ziti-host and the hello-toy chart.
> add chart to deploy hello web app

- charts/ziti-controller/Chart.yaml
- charts/ziti-controller/README.md
- charts/ziti-controller/templates/ca-bundle.yaml
- charts/ziti-controller/templates/ca-edge-signer.yaml
- charts/ziti-controller/templates/ca-router-ctrl-identity.yaml
- charts/ziti-controller/values.yaml
...and adhere to trust-manager best practice of only sourcing bundle from ca.crt (vs. the tls.crt on the CA)
> issue admin client cert

- charts/ziti-controller/Chart.yaml
- charts/ziti-controller/README.md
- charts/ziti-controller/templates/configmap.yaml
- charts/ziti-controller/templates/deployment.yaml
- charts/ziti-controller/values.yaml
- charts/zrok/Chart.yaml
- charts/zrok/README.md
This removes the controller's admin container which only purpose was to run `ziti` CLI. Now the login script is part of the controller container because I don't see any reason to keep them separated.
> remove the unnecessary admin container

- charts/ziti-console/Chart.yaml
...and not "latest". This enables a controlled way to upgrade the ZAC version by upgrading to the latest version of the helm chart. As this is implemented the same way in all the other openziti helm charts, I believe this makes sense to have it the same way for the console.
> AppVersion (for ziti-console chart) should be latest image version

- .github/workflows/release.charts.yml
This changes the behavior of Chart Releaser (`cr`) which automates creating GH releases and updating the Helm index.yaml when a chart is changed in the main branch.
With this variable set, CR will skip releasing a chart if there's already a rease for the current chart version. This will help to resolve the race between forks' and the upstream's chart versions which may be incremented manually or automatically, depending on where the changes originated.
For example, when a fork merges directly to main the chart's version may be superseded by another branch from the upstream, and so the fork's contribution will be released the next time the same chart is modified. 
This avoids the main cause of failed CI jobs in this repo, at the cost of silently delaying the release of some changes. Still, …
> skip existing releases instead of failing the job

- charts/ziti-controller/Chart.yaml
- charts/ziti-controller/README.md
- charts/ziti-controller/templates/deployment.yaml
- charts/ziti-controller/values.yaml
- charts/ziti-host/Chart.yaml
- charts/ziti-host/README.md
- charts/ziti-host/templates/deployment.yaml
- charts/ziti-host/values.yaml
This PR will:
- add the required volume mount parameters for the ziti-host chart so that it can run a container with the spire-agent binary installed.
- add an additional volumes field to the ziti-controller chart to allow for mounting of secrets, configmaps, and PVCs.
> Add Spire Required Volume Mount to Ziti-Host Chart

- charts/ziti-controller/Chart.yaml
- charts/ziti-controller/templates/ca-router-ctrl-identity.yaml
- charts/ziti-controller/templates/ca-web-identity.yaml
- charts/ziti-controller/templates/configmap.yaml
- charts/ziti-controller/templates/deployment.yaml
- charts/ziti-controller/templates/ingress.yaml
- charts/ziti-controller/values.yaml
Also removed a couple instances of `.cluster` as it only co-occurs with `.local` as in `.cluster.local`.
> Make the cluster domain, cluster.local, configurable

- charts/ziti-edge-tunnel/Chart.yaml
- charts/ziti-edge-tunnel/README.md
- charts/ziti-edge-tunnel/README.md.gotmpl
- charts/ziti-edge-tunnel/templates/daemonset.yaml
- charts/ziti-edge-tunnel/values.yaml
Hi @qrkourier,
Related to this [Discourse Topic](https://openziti.discourse.group/t/livenessprobe-for-ziti-edge-tunnel-et-al/2114). Now that `ziti-edge-tunnel tunnel_status` works for the **ziti-edge-tunnel** image, this is the very first implementation of a livenessProbe.
The same would apply for the **ziti-host** helm chart, but I didn't tested it. More than open to discuss delay values, etc.
Thank you! 
Mario
> ziti-edge-tunnel: Add livenessProbe

- charts/ziti-edge-tunnel/values.yaml
Hi @qrkourier,
If we set **nodeSelector** to a default label and want to add another one afterwards, it will result in a list adding the original default one with the new label defined and not just replacing it.
This PR fix to the correct behaviour.
> ziti-edge-tunnel: Fix default nodeSelector

- charts/ziti-edge-tunnel/README.md
- charts/ziti-edge-tunnel/values.yaml
- charts/ziti-host/README.md
- charts/ziti-host/values.yaml
Hi @qrkourier,
This PR remove useless variables **ingress**, and **persistence** from the `values.yaml` and `README.md` files
> ziti-tunnel: Helm Charts cleanup

- charts/ziti-edge-tunnel/Chart.yaml
- charts/ziti-edge-tunnel/values.yaml
Hi @qrkourier,
This is a follow up of #171. Now that we have `jq` installed, lets change the livenessProbe command.
> ziti-edge-tunnel: Update image and use jq for livenessProbe

- charts/ziti-controller/README.md.gotmpl
- charts/ziti-controller/templates/servicemonitor.yaml
- charts/ziti-controller/values.yaml
Hi @qrkourier,
related to #86, I was missing the Prometheus serviceMonitor here. 
FTR, some clarifications, 
1. the **ServiceMonitor** is default enabled but will be used only if the default disabled prometheus service is enabled as well. So there should be no CRD issue anywhere.
2. I had to add an extra default label for the prometheus service, otherwise the serviceMonitor would match all OpenZiti services. Dont know if you agree with the naming.
Let me know if I should change something here.
Thank you!
Mario
> ziti-controller: Add prometheus serviceMonitor

- charts/ziti-controller/values.yaml
Hi @qrkourier,
Set default `insecure_skip_verify: true` otherwise the SAN will not match the pod IP,
See,
```bash
curl --cacert bundle.crt  https://172.26.2.54:9090/metrics curl: (60) SSL: no alternative certificate subject name matches target host name '172.26.2.54'
```
This way the serviceMonitor will always work.
> ziti-controller: set default insecure_skip_verify true

- charts/ziti-controller/Chart.yaml
- charts/ziti-controller/README.md
- charts/ziti-controller/templates/deployment.yaml
- charts/ziti-controller/values.yaml
Allow secrets to be injected as environment variables from the values file:
```
secrets:
- name: SOME_SECRET_ENV
valueFrom:
secretKeyRef:
name: some-secret
key: some_secret_key
```
Helm doesn't support secret compilation in the values file, but this method will replicate the secret config into the configMap so that it renders correctly in the environment.
> Add support for injecting secrets as environment variables (ziti-controller chart)

- charts/zrok/Chart.yaml
- charts/zrok/README.md
- charts/zrok/templates/controller-secrets-configmap.yaml
- charts/zrok/templates/frontend-deployment.yaml
- charts/zrok/templates/frontend-secrets-configmap.yaml
pending availability of https://github.com/openziti/zrok/releases/tag/v0.4.39
> refactor zrok chart for new create account API operation

- charts/ziti-router/README.md
- charts/ziti-router/templates/configmap.yaml
- charts/ziti-router/templates/ingress.yaml
- charts/ziti-router/templates/service.yaml
- charts/ziti-router/values.yaml
Hi @qrkourier ,
I continued you work from you initial PR. It's rebased and in an initial 'works for me in my lab' state ;)
This is the wss server related config I use:
```yaml
additionalVolumes:
- mountPath: /etc/ziti/wss-cert/
name: wss-cert
secretName: nginx-default-cert
volumeType: secret
edge:
additionalListeners:
- advertisedHost: wss.browzer.my.domain
advertisedPort: 443
containerPort: 3023
ingress:
annotations:
kubernetes.io/ingress.allow-http: "false"
nginx.ingress.kubernetes.io/secure-backends: "true"
nginx.ingress.kubernetes.io/ssl-passthrough: "true"
enabled: true
ingressClassName: public
name: edge-wss
protocol: wss
service:
enabled: true
type: ClusterIP
identity:
altServerCerts:
- mode: localFile
serverCert: /etc/ziti/wss-cert/tls.crt
serverKey: /etc/ziti/wss-cert/tls.key …
```
> support secure websocket listener feature in router chart

- charts/ziti-edge-tunnel/README.md.gotmpl
Hello there!
I found it a little bit hard to deploy ziti-edge-tunnel in a multinode cluster as it required a node-local-dns approach, as well as I had a great time debugging a weird CoreDNS behaviour with `bind` plugin and thought it would be a great thing to note in a documentation on how the multinode ziti setup should look like.
Hence the PR.
> Extend documentation for ziti-edge-tunnel with multinode example

- charts/ziti-router/README.md
- charts/ziti-router/templates/deployment.yaml
- charts/ziti-router/values.yaml
Hi @qrkourier,
Currently, the only way to specify the enrollmentJwt is by setting the ```enrollmentJwt``` property in the values for the ziti-router chart. This approach can be cumbersome when automating the deployment process of Ziti controllers and routers, as the enrollmentJwt must be actively acquired from the Ziti controller by calling its API.
**Proposal**:
I propose allowing the specification of a secret name (for a secret which could be created before the actual Ziti router deployment) that holds the enrollmentJwt. This way, an automated process can interact with the Ziti controller API to create the secret in the respective Kubernetes namespace before triggering the router deployment.
Benefits:
- Streamlines the deployment process by reducing manual steps.
- Enhances automation …
> Allow enrollmentJwt from secret (ziti-router-chart) 

- charts/ziti-router/README.md
- charts/ziti-router/templates/pre-upgrade-configmap.yaml
- charts/ziti-router/templates/pre-upgrade-job.yaml
- charts/ziti-router/templates/pre-upgrade-serviceaccount.yaml
- charts/ziti-router/values.yaml
Hi @qrkourier,
I am in the process of deploying the Ziti router chart via ArgoCD and have encountered an issue with the pre-upgrade hook in the router chart. This issue renders the chart unusable with ArgoCD because ArgoCD cannot distinguish between the Helm hooks pre-install and pre-upgrade (as detailed in this [issue](https://github.com/argoproj/argo-cd/issues/7536) and the ArgoCD [documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks)).
**Problem:**
ArgoCD initiates the pre-upgrade hook—which depends on the PVC created by the chart—even during the initial deployment. At this stage, no Persistent Volume Claim (PVC) has been created yet, causing the pre-upgrade hook to fail and preventing the deployment from succeeding.
**Proposal:** 
To resolve this issue, …
> Issue with Pre-Upgrade Hook in Ziti Router Chart When Using ArgoCD

- charts/ziti-controller/README.md.gotmpl
- charts/ziti-router/values.yaml
Add some missing escapes to occurrences of "{ }" blocks in the helm documentation.
> docs: add missing code-block escapes around curly braces

- charts/zrok/templates/pre-delete-hook .yaml
Allow pre-delete-hook job to inherit the affinity and tolerations set in the values file
> Add support for affinity/tolerations to pre-delete hook job

- charts/ziti-router/templates/service.yaml
This should allow for specifying multiple ports on the ziti-router's kubernetes service definition.
> Minor updates to the ziti-router service template

- .github/workflows/miniziti.yml
- charts/ziti-controller/README.md
- charts/ziti-controller/README.md.gotmpl
- charts/ziti-controller/files/chown-cert-manager.bash
document the migration path for the v2 chart breaking change
https://github.com/openziti/helm-charts/blob/upgrade-cert-manager-doc-upgrade/charts/ziti-controller/README.md#breaking-change
migration script: https://github.com/openziti/helm-charts/blob/upgrade-cert-manager-doc-upgrade/charts/ziti-controller/files/chown-cert-manager.bash
> doc upgrade path for v2 breaking change

- charts/ziti-controller/templates/ca-web-identity.yaml
- charts/ziti-controller/templates/configmap.yaml
- charts/ziti-controller/templates/deployment.yaml
Hi, 
this is a fix for #315 😉
It separates the server certificates for the management api and the prometheus metrics.
I'm currently wondering:
- Does the init container (`ziti controller edge init`) need to have access to the certificates?
- Are the `identity.[cert|key]` options required / Is the client certificate required for the management api and prometheus metrics endpoints?
Bye,
Chris
> Fix for: (#315)

- charts/ziti-controller/Chart.yaml
- charts/ziti-controller/README.md
- charts/ziti-controller/README.md.gotmpl
- charts/ziti-controller/templates/ca-ctrl-identity.yaml
- charts/ziti-controller/templates/ca-edge-signer.yaml
- charts/ziti-controller/templates/ca-web-identity.yaml
newest Cert Manager has default private key rotation policy "Always" which I fear would invalidate trust relationships in Ziti's PKI if the root key were rotated, so this is a preventative measure to set an explicit non-default policy for root CA's keys, and the explicit default policy for others.
> set certificate rotation policy; bump controller version

- charts/ziti-controller/templates/traefik-ingressroutetcp.yaml
Avoids the problem of resources overwriting each other when multiple ones being defined (typical on traefik ingress used with separate mgmt hostname).
Naming cloned from the regular ingress resources.
> fix: individual name for each IngressRouteTcp resource

- charts/ziti-controller/templates/traefik-ingressroutetcp.yaml
During trying to make a k3s fresh installation hosting a openziti controller, I stumbled over those old domains (for which no CRDs exists).
This fixes
```
no matches for kind "IngressRouteTCP" in version "traefik.containo.us/v1alpha1"
```
Thank you for all your work!
> update apiVersion domain for remaining traefik-ingressroutetcp resources
